version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: ics-be-dev
    volumes:
      - ics-uploaded-files:/app/src/infrastructure/storage/uploaded_files
    environment:
      - DATABASE_URL=
    ports:
      - "8000:8000"
    network_mode: host

volumes:
  ics-uploaded-files: