version: '3.8'

services:
  app:
    build: .
    container_name: ics-be-dev
    volumes:
      - ics-uploaded-files:/app/src/infrastructure/storage/uploaded_files
    environment:
      - DATABASE_URL=
    ports:
      - "8000:8000"
